/**
 * Observer Agent Prompts
 *
 * Compatibility wrapper for default observer prompt exports.
 * Prompt composition is centralized in observer-modes.ts.
 */

import { buildObserverSystemPrompt } from "./modes";

export {
  OBSERVER_EXTRACTION_INSTRUCTIONS,
  OBSERVER_GUIDELINES,
  OBSERVER_OUTPUT_FORMAT,
} from "./shared";

export {
  EXPLORER_COMPRESSION_GUIDANCE,
  EXPLORER_CONTEXT_INSTRUCTIONS,
  EXPLORER_GUIDELINES,
  EXPLORER_OUTPUT_FORMAT,
  EXPLORER_TASK_CONTEXT,
} from "./modes";

export {
  AgentMode,
  BUGFIXING_COMPRESSION_GUIDANCE,
  BUGFIXING_CONTEXT_INSTRUCTIONS,
  BUGFIXING_EXTRACTION_INSTRUCTIONS,
  BUGFIXING_GUIDELINES,
  BUGFIXING_OUTPUT_FORMAT,
  BUGFIXING_TASK_CONTEXT,
  DEBUGGING_COMPRESSION_GUIDANCE,
  DEBUGGING_CONTEXT_INSTRUCTIONS,
  DEBUGGING_EXTRACTION_INSTRUCTIONS,
  DEBUGGING_GUIDELINES,
  DEBUGGING_OUTPUT_FORMAT,
  DEBUGGING_TASK_CONTEXT,
  getModePrompts,
  MODE_PROMPTS,
  REFACTORING_COMPRESSION_GUIDANCE,
  REFACTORING_CONTEXT_INSTRUCTIONS,
  REFACTORING_EXTRACTION_INSTRUCTIONS,
  REFACTORING_GUIDELINES,
  REFACTORING_OUTPUT_FORMAT,
  REFACTORING_TASK_CONTEXT,
  RESEARCH_COMPRESSION_GUIDANCE,
  RESEARCH_CONTEXT_INSTRUCTIONS,
  RESEARCH_EXTRACTION_INSTRUCTIONS,
  RESEARCH_GUIDELINES,
  RESEARCH_OUTPUT_FORMAT,
  RESEARCH_TASK_CONTEXT,
  TESTING_COMPRESSION_GUIDANCE,
  TESTING_CONTEXT_INSTRUCTIONS,
  TESTING_EXTRACTION_INSTRUCTIONS,
  TESTING_GUIDELINES,
  TESTING_OUTPUT_FORMAT,
  TESTING_TASK_CONTEXT,
} from "./modes";

export const OBSERVER_SYSTEM_PROMPT = buildObserverSystemPrompt("default");
